version: '3.8'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "/home/jose/data/docker/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: tT6mGpGgTTnG
      MYSQL_USER: tradernext_dev
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tradernext
    ulimits:
      nofile:
        soft: "1024"
        hard: "2048"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    ulimits:
      nofile:
        soft: "1024"
        hard: "2048"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ulimits:
      nofile:
        soft: "1024"
        hard: "2048"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ulimits:
      nofile:
        soft: "1024"
        hard: "2048"
